### Variables
@baseUrl = http://localhost:6000/api/exhibitions
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWE5ZWM4MTJiZWYxMjNkYWZkODdmM2YiLCJpYXQiOjE3ODk1MjEwMjUsImV4cCI6MTc4OTUyMTkyNX0.U4k7st0GObWLBlOPD-t0sHt97hIiB9ku5foCB9dad8s

### Create a New Exhibition
POST {{baseUrl}}/createExhibition
Content-Type: application/json

{
  "title": "Modern Art & Tech Exhibition 2026",
  "description": "An immersive digital art exhibition showcasing emerging creators",
  "image": "https://example.com",
  "start_date": "2026-10-15T09:00:00.000Z",
  "end_date": "2026-10-17T17:00:00.000Z",
  "status": "current",
  "highlight": true
}

### Create a New Exhibition
POST {{baseUrl}}/createExhibition
Content-Type: application/json

{
  "title": "Tech Exhibition 2027",
  "description": "An immersive digital art exhibition showcasing emerging creators",
  "image": "https://example.com",
  "start_date": "2026-10-15T09:00:00.000Z",
  "end_date": "2026-10-17T17:00:00.000Z",
  "status": "upcoming",
  "highlight": true
}

###

### Get All Exhibitions (Requires Protected Route)
GET {{baseUrl}}/getAllExhibition
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Get Exhibition by ID (Requires Protected Route)
GET {{baseUrl}}/6aa947a8f81122448d1ae62a
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Delete an Exhibition (Requires Admin Route)
DELETE {{baseUrl}}/6aa947a8f81122448d1ae62a
Authorization: Bearer {{authToken}}
Content-Type: application/json
